- name: download zabbix repo
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
    dest: /home/user/

- name: install zabbix repo
  apt:
    deb: /home/user/zabbix-release_6.0-4+ubuntu22.04_all.deb
  
- name: update apt cache
  apt:
    update_cache: yes