- name: restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted

- name: restart apache2
  systemd:
    name: apache2
    state: restarted

- name: restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted