- name: update apt cache
  apt:
    update_cache: yes

- name: install gnupg, apt-transport-https
  apt: 
    name: 
    - apt-transport-https
    - gnupg
    state: present

- name: download filebeat
  ansible.builtin.get_url:  
    url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.14-amd64.deb
    dest: /home/user/